version: '3'

rpc:
  listen: tcp://127.0.0.1:6001

kv:
  local:
    driver: memory
    config: { }

server:
  on_init:
    command: 'php app.php migrate'
  command: 'php app.php'
  relay: pipes

logs:
  level: ${RR_LOG_LEVEL:-error}

service:
  dolt:
    service_name_in_log: true
    remain_after_exit: true
    restart_sec: 1
    command: "./dolt sql-server --data-dir=.db"
